name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload code to S3
      run: |
        zip -r kanri_function.zip app/
        echo "Uploading kanri_function.zip to S3 with ref name: ${{ github.ref_name }}..."
        aws s3 cp kanri_function.zip s3://kanri-project-cl/kanri-code-${{ github.ref_name }}.zip

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name KanriLambda \
          --s3-bucket kanri-project-cl \
          --s3-key kanri-code-${{ github.ref_name }}.zip

    - name: Update Lambda alias
      run: |
        FUNCTION_VERSION=$(aws lambda publish-version --function-name KanriLambda --query Version --output text)
        aws lambda update-alias \
          --function-name KanriLambda \
          --name ${{ github.ref_name }} \
          --function-version $FUNCTION_VERSION
